<a href="https://colab.research.google.com/github/Briana-Pinales/analytics-repo/blob/main/Briana_Pinales_3_1_NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Unit 3 - Advanced Python - NumPy - Assignment #1  

## 1. Environment Set up

In [2]:
import numpy as np

In [3]:
#Dataset from summer Olympic London, year 2012
np_olympic_country = np.array(['GBR','China','RUS','US','KOR','JPN','GER'])
np_olympic_country_Gold = np.array([29,38,24,46,13,7,11])
np_olympic_country_Silver = np.array([17,28,25,28,8,14,11])
np_olympic_country_Bronze = np.array([19,22,32,29,7,17,14])

## 2.	Find country with maximum gold

In [20]:
np_olympic_country_Gold.max()

46

In [24]:
np.where(np_olympic_country_Gold==46)

(array([3]),)

In [23]:
np_olympic_country[3]

'US'

This is what i thought i had to do before i asked for help

In [4]:
print(np_olympic_country)
print(np_olympic_country_Gold)

['GBR' 'China' 'RUS' 'US' 'KOR' 'JPN' 'GER']
[29 38 24 46 13  7 11]


In [5]:
max_gold = np.array([[np_olympic_country],[np_olympic_country_Gold]])

In [6]:
max_gold

array([[['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER']],

       [['29', '38', '24', '46', '13', '7', '11']]], dtype='<U21')

In [7]:
print(max_gold)

[[['GBR' 'China' 'RUS' 'US' 'KOR' 'JPN' 'GER']]

 [['29' '38' '24' '46' '13' '7' '11']]]


In [8]:
max_gold.reshape(2,7)

array([['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'],
       ['29', '38', '24', '46', '13', '7', '11']], dtype='<U21')

In [9]:
max_gold.transpose()

array([[['GBR', '29']],

       [['China', '38']],

       [['RUS', '24']],

       [['US', '46']],

       [['KOR', '13']],

       [['JPN', '7']],

       [['GER', '11']]], dtype='<U21')

In [10]:
gold = max_gold.reshape(7,2)

In [11]:
gold

array([['GBR', 'China'],
       ['RUS', 'US'],
       ['KOR', 'JPN'],
       ['GER', '29'],
       ['38', '24'],
       ['46', '13'],
       ['7', '11']], dtype='<U21')

In [12]:
max(gold[:,1])

'US'

In [13]:
#I'm not exactly sure how but i got the right answer

## 3.	Find countries with more than 20 gold medals

In [14]:
np_olympic_country_Gold

array([29, 38, 24, 46, 13,  7, 11])

In [15]:
passing = np_olympic_country_Gold > 20

In [26]:
np_olympic_country_Gold[passing]

array([29, 38, 24, 46])

In [25]:
np.where(np_olympic_country_Gold[passing]

(array([0, 1, 2, 3]),)

In [29]:
print(np_olympic_country[0])

GBR


In [30]:
print(np_olympic_country[1])

China


In [34]:
print(np_olympic_country[2])

RUS


In [35]:
print(np_olympic_country[3])

US
